// <auto-generated />
using System;
using Amani.ImportadosERP.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Amani.ImportadosERP.Infra.Data.Migrations
{
    [DbContext(typeof(AmaniDbContext))]
    [Migration("20260701002458_AddProdutoApresentacoesFracionadas")]
    partial class AddProdutoApresentacoesFracionadas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CategoriaDespesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NomeNormalizado")
                        .IsUnique();

                    b.ToTable("categoria_despesas", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Compra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Acrescimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Criada");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataCompra", "Status")
                        .HasDatabaseName("IX_compras_DataCompra_Status");

                    b.ToTable("compras", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Acrescimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.ToTable("compra_items", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItemPerda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompraItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPerda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CompraItemId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("compra_item_perdas", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItemRecebimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompraItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRecebimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EstoqueMovimentacaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CompraItemId");

                    b.HasIndex("EstoqueMovimentacaoId")
                        .IsUnique();

                    b.HasIndex("ProdutoId");

                    b.ToTable("compra_item_recebimentos", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ConfiguracaoFormaPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("PercentualTaxa")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamento")
                        .IsUnique();

                    b.ToTable("configuracoes_formas_pagamento", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ContaReceber", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("VendaId");

                    b.HasIndex("CreatedAt", "DataVencimento")
                        .HasDatabaseName("IX_contas_receber_CreatedAt_DataVencimento");

                    b.ToTable("contas_receber", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Despesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaDespesaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCompetencia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaDespesaId");

                    b.HasIndex("DataCompetencia")
                        .HasDatabaseName("IX_despesas_DataCompetencia");

                    b.ToTable("despesas", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.DespesaOperadora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("PercentualTaxa")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("ValorBruto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("despesas_operadora", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.EstoqueMovimentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompraId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CompraItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<long?>("QuantidadeExataDenominador")
                        .HasColumnType("bigint");

                    b.Property<long?>("QuantidadeExataNumerador")
                        .HasColumnType("bigint");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("VendaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("VendaItemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompraId");

                    b.HasIndex("CompraItemId");

                    b.HasIndex("VendaId");

                    b.HasIndex("VendaItemId");

                    b.HasIndex("ProdutoId", "Data", "Tipo")
                        .HasDatabaseName("IX_estoque_movimentacoes_ProdutoId_Data_Tipo");

                    b.ToTable("estoque_movimentacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_estoque_movimentacoes_Quantidade", "\"Quantidade\" > 0");

                            t.HasCheckConstraint("CK_estoque_movimentacoes_QuantidadeExata", "(\"QuantidadeExataNumerador\" IS NULL AND \"QuantidadeExataDenominador\" IS NULL) OR (\"QuantidadeExataNumerador\" IS NOT NULL AND \"QuantidadeExataDenominador\" IS NOT NULL AND \"QuantidadeExataNumerador\" > 0 AND \"QuantidadeExataDenominador\" > 0 AND \"Quantidade\" = round(\"QuantidadeExataNumerador\"::numeric / \"QuantidadeExataDenominador\", 12))");
                        });
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.EventoAutenticacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LoginInformado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MensagemSegura")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UsuarioId");

                    b.ToTable("eventos_autenticacao", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.EventoFinanceiro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Tipo", "Data")
                        .HasDatabaseName("IX_eventos_financeiros_Tipo_Data");

                    b.ToTable("eventos_financeiros", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Fornecedor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("fornecedores", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.PagamentoRecebido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContaReceberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorBrutoLiquidado")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ContaReceberId");

                    b.HasIndex("DataPagamento")
                        .HasDatabaseName("IX_pagamentos_recebidos_DataPagamento");

                    b.ToTable("pagamentos_recebidos", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Custo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("FornecedorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("produtos", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ProdutoApresentacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FatorDenominador")
                        .HasColumnType("bigint");

                    b.Property<long>("FatorNumerador")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PermiteCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("PermiteVenda")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("PrecoVenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId", "Nome")
                        .IsUnique();

                    b.HasIndex("ProdutoId", "Ativo", "PermiteVenda");

                    b.ToTable("produto_apresentacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_produto_apresentacoes_FatorAteUm", "\"FatorNumerador\" <= \"FatorDenominador\"");

                            t.HasCheckConstraint("CK_produto_apresentacoes_FatorDenominador", "\"FatorDenominador\" > 0");

                            t.HasCheckConstraint("CK_produto_apresentacoes_FatorNumerador", "\"FatorNumerador\" > 0");

                            t.HasCheckConstraint("CK_produto_apresentacoes_PermiteCompra", "\"PermiteCompra\" = FALSE");
                        });
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LoginNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("OrigemProvisionamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LoginNormalizado")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Acrescimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("PercentualTaxaAplicado")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DataVenda", "Cancelada")
                        .HasDatabaseName("IX_vendas_DataVenda_Cancelada");

                    b.ToTable("vendas", (string)null);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.VendaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Acrescimo")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ApresentacaoNomeSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Desconto")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("FatorConversaoAplicado")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<long?>("FatorDenominadorAplicado")
                        .HasColumnType("bigint");

                    b.Property<long?>("FatorNumeradorAplicado")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("ProdutoApresentacaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QuantidadeConvertidaEstoque")
                        .HasPrecision(28, 12)
                        .HasColumnType("numeric(28,12)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoApresentacaoId");

                    b.HasIndex("VendaId");

                    b.ToTable("venda_items", null, t =>
                        {
                            t.HasCheckConstraint("CK_venda_items_ApresentacaoSnapshot", "(\"ProdutoApresentacaoId\" IS NULL AND \"ApresentacaoNomeSnapshot\" IS NULL AND \"FatorNumeradorAplicado\" IS NULL AND \"FatorDenominadorAplicado\" IS NULL AND \"FatorConversaoAplicado\" IS NULL AND \"QuantidadeConvertidaEstoque\" IS NULL) OR (\"ProdutoApresentacaoId\" IS NOT NULL AND \"ApresentacaoNomeSnapshot\" IS NOT NULL AND \"FatorNumeradorAplicado\" > 0 AND \"FatorDenominadorAplicado\" > 0 AND \"FatorNumeradorAplicado\" <= \"FatorDenominadorAplicado\" AND \"FatorConversaoAplicado\" > 0 AND \"QuantidadeConvertidaEstoque\" > 0 AND \"FatorConversaoAplicado\" = round(\"FatorNumeradorAplicado\"::numeric / \"FatorDenominadorAplicado\", 12) AND \"QuantidadeConvertidaEstoque\" = round(\"Quantidade\"::numeric * \"FatorNumeradorAplicado\" / \"FatorDenominadorAplicado\", 12))");
                        });
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItem", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Compra", "Compra")
                        .WithMany("Items")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItemPerda", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Compra", "Compra")
                        .WithMany("Perdas")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.CompraItem", "CompraItem")
                        .WithMany("Perdas")
                        .HasForeignKey("CompraItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("CompraItem");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItemRecebimento", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Compra", "Compra")
                        .WithMany("Recebimentos")
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.CompraItem", "CompraItem")
                        .WithMany("Recebimentos")
                        .HasForeignKey("CompraItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.EstoqueMovimentacao", "EstoqueMovimentacao")
                        .WithOne()
                        .HasForeignKey("Amani.ImportadosERP.Domain.Entities.CompraItemRecebimento", "EstoqueMovimentacaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Compra");

                    b.Navigation("CompraItem");

                    b.Navigation("EstoqueMovimentacao");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ContaReceber", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Despesa", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany()
                        .HasForeignKey("CategoriaDespesaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaDespesa");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.DespesaOperadora", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.EstoqueMovimentacao", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Compra", null)
                        .WithMany()
                        .HasForeignKey("CompraId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.CompraItem", "CompraItem")
                        .WithMany()
                        .HasForeignKey("CompraItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Venda", null)
                        .WithMany()
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.VendaItem", "VendaItem")
                        .WithMany()
                        .HasForeignKey("VendaItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CompraItem");

                    b.Navigation("VendaItem");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.EventoAutenticacao", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.PagamentoRecebido", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.ContaReceber", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("ContaReceberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Produto", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Fornecedor", null)
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ProdutoApresentacao", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Produto", "Produto")
                        .WithMany("Apresentacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.VendaItem", b =>
                {
                    b.HasOne("Amani.ImportadosERP.Domain.Entities.ProdutoApresentacao", "ProdutoApresentacao")
                        .WithMany()
                        .HasForeignKey("ProdutoApresentacaoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Amani.ImportadosERP.Domain.Entities.Venda", "Venda")
                        .WithMany("Items")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProdutoApresentacao");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Compra", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Perdas");

                    b.Navigation("Recebimentos");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.CompraItem", b =>
                {
                    b.Navigation("Perdas");

                    b.Navigation("Recebimentos");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.ContaReceber", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Apresentacoes");
                });

            modelBuilder.Entity("Amani.ImportadosERP.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
